version: "3"
services:
  react-young-conf:
    build: ./
    stdin_open: true
    ports:
      - "3000:3000"
    networks:
      - mern-app
    volumes:
      - ./server/:/usr/src/app
      - /usr/src/app/node_modules
  express-server:
    build: ./server/
    ports:
      - "5000:5000"
    networks:
      - mern-app
    volumes:
      - ./server/:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongo
  mongo:
    image: mongo:5.0.0-focal
    ports:
      - "27017:27017"
    networks:
      - mern-app
    volumes:
      - mongo-data:/data/db
networks:
  mern-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local
